Fix ceph-relation-changed error
TypeError: 'str' object is not callable
After recent interface change

Change-Id: I7a45b1ffe7d71bd44201a72510d6b56a1e1a4824
Closes-Bug: #1893445
(cherry picked from commit 50c11d0e995bec63bd9bf52d47750edd84b0f98a)